language: scala

jdk: openjdk9

scala:
  - 2.13.1
  - 2.13.2
os:
  - linux
  - osx

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - chmod +x ./gradlew
  - export DISPLAY=:99.0

install: true

script:
  - sbt ++$TRAVIS_SCALA_VERSION test